[package]
name = "eeprom24x"
version = "0.3.0"
authors = ["Diego Barrios Romero <eldruin@gmail.com>"]
repository = "https://github.com/eldruin/eeprom24x-rs"
license = "MIT OR Apache-2.0"
description = "Platform-agnostic Rust driver for the 24x series serial EEPROMs."
readme = "README.md"
keywords = ["eeprom", "i2c", "driver", "embedded-hal-driver"]
categories = ["embedded", "hardware-support", "no-std"]
homepage = "https://github.com/eldruin/eeprom24x-rs"
documentation = "https://docs.rs/eeprom24x"
include = [
    "**/*.rs",
    "/Cargo.toml",
    "/CHANGELOG.md",
    "/README.md",
    "/LICENSE-MIT",
    "/LICENSE-APACHE",
]

[badges]
travis-ci = { repository = "eldruin/eeprom24x-rs", branch = "master" }
coveralls = { repository = "eldruin/eeprom24x-rs", branch = "master", service = "github" }
maintenance = { status = "actively-developed" }

[dependencies]
embedded-hal = "0.2"

[dev-dependencies]
linux-embedded-hal = "0.2"
embedded-hal-mock = "0.4"

[profile.release]
lto = true
